/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.homesoft.spark.list;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class SomeTest {
    @Test
    public void test() {
        assertTrue(true);
    }
}
