/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.homesoft.spark;

import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;

public class SparkClient {
    public static void main(String[] args) {
        System.out.println("Hey there!");

        final SparkSession spark = SparkSession.builder().appName("SampleSparkClient").master("local[*]").getOrCreate();
        final Dataset<Row> ids = spark.read().format("excel").load();
        ids.show();
    }
}
