/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.homesoft.spark;

import org.apache.spark.sql.SparkSession;

public class SparkClient {
    public static void main(String[] args) {
        System.out.println("Hey there!");

        final SparkSession spark = SparkSession.builder().appName("SampleSparkClient").master("local[*]").getOrCreate();
        final boolean useCrealyticsImplementation = true;
        //noinspection ConstantConditions
        if (useCrealyticsImplementation) {
            spark.read()
                    .format("com.crealytics.spark.excel")
                    .option("inferSchema", true)
                    .option("header", true)
                    .load("sample.xlsx")
                    .registerTempTable("excel");
        } else {
            spark.read()
                    .format("com.homesoft.spark.SparkConnector")
                    .option("sheetName", "Table1")
                    .load("sample.xlsx")
                    .registerTempTable("excel");
        }

        spark.sql("select * from excel").show();
    }
}
